# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22535414a2bec48599d3ba72efa2876eeb7f95bc313e67e10c2a9f5ff84be6206915b7cc99f868e7fbf1dfd974b30e7023d70ab2043fb9795034f215b66167ec

test:
  secret_key_base: 20988a6819b8f96da2182be0366493466b41d0b01c5a2ed9113c1267f77cbcd1fe75368bbf8cac5a482a89f5677545f00cb05505d5c27b01f8b3f8ca894766a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
